#####################
# Dockerfile to build hic2cool container image
# Based on Ubuntu
####################

FROM ubuntu

MAINTAINER noah.burget@pennmedicine.upenn.edu

RUN apt-get update && apt-get install -y python3-pip

RUN pip install hic2cool
     

